app/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import views

#app_name = "homedepot"


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    
    # ...
]

app_patterns = ([
    path("", views.index, name="index"),
    path("kardex_entradas_almacen/", views.kardex_entradas_almacen, name="kardex_entradas_almacen"),
    path("kardex_almacen/", views.kardex_almacen, name="kardex_almacen"),
    path("contador_usados/", views.contador_usados, name="contador_usados"),
    path("kardex/", views.kardex_usados, name="kardex"),
    path("salidas_proveedor/", views.salidas_proveedor, name="salidas_proveedor"),
    path("kardex_garantia/", views.kardex_garantia, name="kardex_garantia"),
    path("contador_cliente/<int:id>/", views.contador_cliente, name="contador_cliente"),
    path("sincronizar_kardex/", views.sincronizar_kardex, name="sincronizar_kardex"),
    path("regenerar_existencias_kardex/", views.regenerar_existencias_kardex, name="regenerar_existencias_kardex"),
    path("catalogo_cascos/", views.catalogo_cascos, name="catalogo_cascos"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    
    path("catalogo_clientes/", views.catalogo_clientes, name="catalogo_clientes"),
    path("agregar_casco/", views.agregar_casco, name="agregar_casco"),
    path("agregar_cliente/", views.agregar_cliente, name="agregar_cliente"),
    path("editar_casco/<int:id>", views.editar_casco, name="editar_casco"),
    path("editar_cliente/<int:id>", views.editar_cliente, name="editar_cliente"),
    path("agregar_entrada/", views.agregar_entrada, name="agregar_entrada"),
    path("agregar_salida_garantia_proveedor/",views.agregar_salida_garantia_proveedor, name="agregar_salida_garantia_proveedor"),
    path("agregar_salida_usado_proveedor/",views.agregar_salida_usado_proveedor, name="agregar_salida_usado_proveedor"),
    path("agregar_salida/", views.agregar_salida, name="agregar_salida"),
    path("graficas_movimientos/", views.graficas_movimientos, name="graficas_movimientos"),
    path("cancelar_movimiento/<int:id>", views.cancelar_movimiento, name="cancelar_movimiento"),
    
    path("ver_vale/<int:id>/", views.ver_vale, name="ver_vale"),
    #paht("nota_de_credito/<int:id>", views.ver_nota_de_credito, name="ver_nota_de_credito"),
    path("notas_credito/", views.notas_credito, name="notas_credito"),
    path("nota_credito/<int:id>", views.nota_credito, name="nota_credito"),
    path("agregar_nota_credito/<int:id>", views.agregar_nota_credito, name="agregar_nota_credito"),
    path("gmroi_cliente/<int:id>", views.gmroi_cliente, name="gmroi_cliente"),

    path("ordenes_compra_domicilio/", views.ordenes_compra_domicilio, name="ordenes_compra_domicilio"),
    path("agregar_orden_compra_domicilio/", views.agregar_orden_compra_domicilio, name="agregar_orden_compra_domicilio"),
    path("ajax_get_cliente/<str:term>/", views.ajax_get_cliente, name="ajax_get_cliente"),
    path("ajax_clientes_ac/", views.ajax_clientes_ac, name="ajax_clientes_ac"),
    path("ajax_crear_nota_credito/", views.ajax_crear_nota_credito, name="ajax_crear_nota_credito"),
    path("ajax_get_folios_by_proveedor/", views.ajax_get_folios_by_proveedor,name="ajax_get_folios_by_proveedor"),
    path('sentry-debug/', trigger_error),

    
], "app")

urlpatterns = [
    path("", include(app_patterns)),

    path("configuracion/", include("configuracion.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("atshell/", include("atshell.urls")),
]

# archivos subidos al sistema
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# static files
urlpatterns = urlpatterns + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

configuracion/urls.py
from django.urls import path
from . import views

app_name  = "configuracion"
urlpatterns = [
    #Definiciones
    path(
        "configuracion/personalizacion_de_sistema/", 
        views.configuracion, {}, 
        "configuracion"
    ),
]

configuracion/models.py
import pytz
from django.db import models
from django.utils import timezone

class Configuracion(models.Model):
    MX_TIMEZONES = [(x, x) for x in pytz.country_timezones["MX"]]
    zona_horaria = models.CharField(
        max_length=255,
        choices=MX_TIMEZONES,
        null=True,
        blank=True,
        default="America/Mexico_City",
        verbose_name="Zona Horaria",
    )
    project_name = models.CharField(max_length=255, blank=True, null=True)
    logo = models.ImageField(upload_to="conf/", null=True, blank=True)
    color_empresa = models.CharField(
        max_length=10, blank=True, null=True, default="#F96302"
    )
    theme_primary_color = models.CharField(
        max_length=10, blank=True, null=True, default="#F96302"
    )
    theme_secondary_color = models.CharField(
        max_length=10, blank=True, null=True, default="#989898"
    )
    api_key = models.CharField(max_length=500, default='', blank=True, null=True, verbose_name='API-KEY')
    fecha_inicio = models.DateField(default=timezone.now)
    saldo_inicial = models.DecimalField(decimal_places=2, max_digits=12, default=0)

configuracion/forms.py
from django import forms
from django.forms.models import ModelChoiceField

from tools.forms import BootstrapModelForm, BootstrapForm, CalendarDateField

from .models import (
    Configuracion,
   
)   

class ConfiguracionForm(BootstrapModelForm):
    class Meta:
        model = Configuracion
        fields = (
            "project_name",
            "logo",
            "color_empresa",
            "theme_primary_color",
            "theme_secondary_color",
            "zona_horaria",
            "api_key",
            "fecha_inicio",
            "saldo_inicial",
            )
        
    fecha_inicio = CalendarDateField()

configuracion/views.py
import pprint
ap = pprint.PrettyPrinter(indent=4)

import json
import datetime

from io import TextIOWrapper
from functools import partial, wraps

from django.forms.models import modelformset_factory
from django.http import Http404
from django.contrib import messages
from django.db.models import Q, Sum
from django.urls import reverse
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


from tools.classes import ExcelFile
from tools.forms import EMPTY_CHOICE, ELEMENTOS_PAGINA
from tools.functions import (
    json_response, 
    error_response, 
    list_view, 
    to_int, 
    safe_division, 
    render_pdf,
)
from .models import (
    Configuracion,
)
from .forms import (

    ConfiguracionForm,
)


def configuracion(request, tipo=None):
    try:
        configuracion = Configuracion.objects.get()
    except:
        configuracion = Configuracion.objects.get_or_create()[0]

    form = ConfiguracionForm(instance=configuracion)    
    if request.method == "POST":
        form = ConfiguracionForm(request.POST, request.FILES, instance=configuracion)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Los datos han sido guardados correctamente."
            )
        return redirect(".")

    return render(
        request,
        "configuracion/configuracion.html",
        {
            "title": "",
            "form":form,
            "NODO_BREADCRUMB": "configuracion:configuracion",
        },
    )
    

configuracion/templates/configuracion/configuracion.html
{% extends "app/base.html" %}
{% load static custom_tags thumbnail %}
{% block extra_head %}

<link rel="stylesheet" href="{% static "app/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" %}" />
<script src="{% static "app/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js" %}"></script>
{% endblock extra_head %}
{% block contenido %}
<div class="container-fluid">
    <form action="." method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="card my-2">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            {% if form.instance.logo %}
                            <div class="img-thumbnail d-inline-block" style="margin:10px 0">
                                {% thumbnail form.instance.logo "x65" format="PNG" as im %}
                                    <img src="{{ im.url }}"  class="img-fluid">
                                {% endthumbnail %}
                            </div>
                            <label for="" class="d-block">Cambiar Logotipo:</label>
                            {% else %}
                            <label for="" class="d-block">Logotipo:</label>
                            {% endif %}
                            {{ form.logo }}
                            {{ form.logo.errors }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.project_name.label_tag }}
                            {{ form.project_name }}
                            {{ form.project_name.errors }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.color_empresa.label_tag }}
                            {{ form.color_empresa }}
                            {{ form.color_empresa.errors }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.theme_primary_color.label_tag }}
                            {{ form.theme_primary_color }}
                            {{ form.theme_primary_color.errors }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.theme_secondary_color.label_tag }}
                            {{ form.theme_secondary_color }}
                            {{ form.theme_secondary_color.errors }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.zona_horaria.label_tag }}
                            {{ form.zona_horaria }}
                            {{ form.zona_horaria.errors }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.api_key.label_tag }}
                            {{ form.api_key }}
                            {{ form.api_key.errors }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.fecha_inicio.label_tag }}
                            {{ form.fecha_inicio }}
                            {{ form.fecha_inicio.errors }}
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group list-inline-item">
                            {{ form.saldo_inicial.label_tag }}
                            {{ form.saldo_inicial }}
                            {{ form.saldo_inicial.errors }}
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" id="guardarSolicitud" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
            
    </form>
</div>

{% endblock contenido %}
{% block js %}
<script>
    $(function () {
        $("#id_color_empresa").colorpicker()
        $("#id_theme_primary_color").colorpicker()
        $("#id_theme_secondary_color").colorpicker()
    });
</script>
{% endblock js %}