app/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import views

#app_name = "homedepot"


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    
    # ...
]

app_patterns = ([
    path("", views.index, name="index"),
    path("kardex_entradas_almacen/", views.kardex_entradas_almacen, name="kardex_entradas_almacen"),
    path("kardex_almacen/", views.kardex_almacen, name="kardex_almacen"),
    path("contador_usados/", views.contador_usados, name="contador_usados"),
    path("kardex/", views.kardex_usados, name="kardex"),
    path("salidas_proveedor/", views.salidas_proveedor, name="salidas_proveedor"),
    path("kardex_garantia/", views.kardex_garantia, name="kardex_garantia"),
    path("contador_cliente/<int:id>/", views.contador_cliente, name="contador_cliente"),
    path("sincronizar_kardex/", views.sincronizar_kardex, name="sincronizar_kardex"),
    path("regenerar_existencias_kardex/", views.regenerar_existencias_kardex, name="regenerar_existencias_kardex"),
    path("catalogo_cascos/", views.catalogo_cascos, name="catalogo_cascos"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    
    path("catalogo_clientes/", views.catalogo_clientes, name="catalogo_clientes"),
    path("agregar_casco/", views.agregar_casco, name="agregar_casco"),
    path("agregar_cliente/", views.agregar_cliente, name="agregar_cliente"),
    path("editar_casco/<int:id>", views.editar_casco, name="editar_casco"),
    path("editar_cliente/<int:id>", views.editar_cliente, name="editar_cliente"),
    path("agregar_entrada/", views.agregar_entrada, name="agregar_entrada"),
    path("agregar_salida_garantia_proveedor/",views.agregar_salida_garantia_proveedor, name="agregar_salida_garantia_proveedor"),
    path("agregar_salida_usado_proveedor/",views.agregar_salida_usado_proveedor, name="agregar_salida_usado_proveedor"),
    path("agregar_salida/", views.agregar_salida, name="agregar_salida"),
    path("graficas_movimientos/", views.graficas_movimientos, name="graficas_movimientos"),
    path("cancelar_movimiento/<int:id>", views.cancelar_movimiento, name="cancelar_movimiento"),
    
    path("ver_vale/<int:id>/", views.ver_vale, name="ver_vale"),
    #paht("nota_de_credito/<int:id>", views.ver_nota_de_credito, name="ver_nota_de_credito"),
    path("notas_credito/", views.notas_credito, name="notas_credito"),
    path("nota_credito/<int:id>", views.nota_credito, name="nota_credito"),
    path("agregar_nota_credito/<int:id>", views.agregar_nota_credito, name="agregar_nota_credito"),
    path("gmroi_cliente/<int:id>", views.gmroi_cliente, name="gmroi_cliente"),

    path("ordenes_compra_domicilio/", views.ordenes_compra_domicilio, name="ordenes_compra_domicilio"),
    path("agregar_orden_compra_domicilio/", views.agregar_orden_compra_domicilio, name="agregar_orden_compra_domicilio"),
    path("ajax_get_cliente/<str:term>/", views.ajax_get_cliente, name="ajax_get_cliente"),
    path("ajax_clientes_ac/", views.ajax_clientes_ac, name="ajax_clientes_ac"),
    path("ajax_crear_nota_credito/", views.ajax_crear_nota_credito, name="ajax_crear_nota_credito"),
    path("ajax_get_folios_by_proveedor/", views.ajax_get_folios_by_proveedor,name="ajax_get_folios_by_proveedor"),
    path('sentry-debug/', trigger_error),

    
], "app")

urlpatterns = [
    path("", include(app_patterns)),

    path("configuracion/", include("configuracion.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("atshell/", include("atshell.urls")),
]

# archivos subidos al sistema
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# static files
urlpatterns = urlpatterns + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

usuarios/urls.py
from usuarios import views
from django.urls import path

app_name = "usuarios"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("acceso_denegado/", views.acceso_denegado, name="acceso_denegado"),
    path("", views.usuarios, name="usuarios"),
    path("roles", views.roles, name="roles"),
    path("perfil", views.perfil, name="perfil"),
    path("editar_usuario/<int:id>/", views.usuario, name="usuario"),
    path("agregar_usuario/", views.usuario, name="usuario"),
    path("inicios_sesion/", views.inicios_sesion, name="inicios_sesion"),
    path("importar_usuarios/", views.importar_usuarios, name="importar_usuarios"),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("reset_password/<str:token>/", views.reset_password, name="reset_password"),
    path(
        "reenviar_correo_bienvenida/<int:id>/",
        views.reenviar_correo_bienvenida,
        name="reenviar_correo_bienvenida",
    ),
    path(
        "ajax/cambiar_password/",
        views.cambiar_password,
        name="cambiar_password",
    ),
    path(
        "ajax/validar_autorizacion/<int:id>/",
        views.ajax_validar_autorizacion,
        name="ajax_validar_autorizacion",
    ),
    path("agregar_rol/", views.agregar_rol, name="agregar_rol"),
    path("editar_rol/<int:id>/", views.editar_rol, name="editar_rol"),
    path("eliminar_rol/<int:id>/", views.eliminar_rol, name="eliminar_rol"),
    # ajax
    path("ajax/set_sidebar/", views.ajax_set_sidebar, name="set_sidebar"),
    path(
        "ajax/set_permiso_rol/<int:id>/",
        views.ajax_set_permiso_rol,
        name="set_permiso_rol",
    ),
]

app/templates/app/base.html
{% extends "app/clean_base.html" %}
{% load thumbnail static custom_tags %}

{% block _extra_head %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
<link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

{% if request.user.perfil.tema_tamano_fuente %}
<style>
.btn, 
.form-control,
body{
    font-size: {{ request.user.perfil.tema_tamano_fuente }}px
}
.thead { background-color: {{ configuracion.color_empresa }}; }
</style>
{% endif %}

{% block extra_head %}
{% endblock extra_head %}
{% endblock _extra_head %}

{% block _contenido %}
<div class="application-wrapper {% if request.user.perfil.sidebar_colapsado %} sidebar-collapsed{% endif %}">
    <div class="header d-flex">
        <div class="logo">
            <a href="{% url 'app:index' %}" class="d-flex align-items-center justify-content-center px-2">
                {% if configuracion.logo %}
                {% thumbnail configuracion.logo "x65" format="PNG" as im %}
                <img src="{{ im.url }}"  class="img-fluid">
                {% endthumbnail %}
                {% else %}
                <img src="https://placehold.it/120x60" class="img-fluid">
                {% endif %}
            </a>
        </div>
        <div class="right-items">
            <div class="d-flex justify-content-between align-items-center">
                <div class="app-breadcrums">
                </div>
                <div  class="app-periodo" id="btn-periodo">{% block top_right_content %} {% endblock %}</div>
                <div>
                    <div class="usuario-dropdown relative">
                        <a href="#usuarioSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="icon ion-md-person"></i> {{ request.user }}</a>
                        <ul class="collapse list-unstyled sub" id="usuarioSubmenu">
                            <li>
                                <a href="{% url 'usuarios:perfil' %}"><i class="icon ion-md-contact"> Mi Perfil</i></a>
                            </li>
                            <li>
                                <a href="{% url 'usuarios:logout' %}"><i class="icon ion-md-log-out"> Salir</i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="d-flex">
        <div class="sidebar full-content-height bg-white">
            <div class="menu-box">
                <ul class="list-unstyled menu-list m-0">
                    {% for elem in MENU %}
                    <li data-parent="{{ elem.id }}">
                        <a href="#{{ elem.id }}Submenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" title="{{ elem.nombre }}">
                            <i class="{{ elem.icono }}"></i> <span>{{ elem.nombre }}</span>
                        </a>
                        {% if elem.children %}
                        <ul class="collapse list-unstyled sub" id="{{ elem.id }}Submenu">
                            
                            {% for child in elem.children %}

                                <li>
                                    {% if child.url %}
                                        <a data-child="{{ child.id }}" href="{{ child.url }}">{{ child.nombre }}</a>
                                    {% else %}
                                        <a data-child="{{ child.id }}" href="{% url child.id %}">{{ child.nombre }}</a>
                                    {% endif %}
                                </li>
                                
                            {% endfor %}

                        </ul>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div title="Fecha: {{ VERSION_TIMESTAMP  }}" class="version">Versión: <b>{{ VERSION|default:'N/A' }}</b></div>
            <div class="version zona-horaria" title="Zona Horaria">{{ request.session.django_timezone }}</div>
            <a href="#" class="toggle-sidebar">
                <i class="icon ion-md-arrow-back"></i>
            </a>
        </div>

        <div class="right-content">
            <div class="flash-messages-box">
            {% include "app/includes/flash_messages.html" %}
            </div>
            {% block contenido %}
            {% endblock contenido %}
        </div>
    </div>
</div>
{% endblock _contenido %}


{% block _js %}
<script src="{% static "app/js/jquery.formset.js" %}?v=1.1.6"></script>
<script type="text/javascript" src="{% static "app/js/moment.min.js" %}"></script>
<script type="text/javascript" src="{% static "app/js/moment.es.js" %}"></script>
<script type="text/javascript" src="{% static "app/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<script type="text/javascript" src=""></script>

<script>

    function submit_order(order){
        $("#id_order").val(order);
        $("form").submit();
    }


    // jQuery plugin to prevent double submission of forms
    jQuery.fn.preventDoubleSubmission = function() {
      $(this).on('submit',function(e){
        var $form = $(this);
        if ($form.data('submitted') === true) {
          // Previously submitted - don't submit again
          return false

        } else {
          // Mark it so that the next submit can be ignored
          $form.data('submitted', true);
          if (!$form.data("hideLoading")) {
            showLoading()
          } else {
            $form.data("hideLoading", false)
          }
        }
      });

      // Keep chainability
      return this;
    };

    $.fn.formset.defaults.addText = '<i class="icon ion-md-add"></i> Agregar';
    $.fn.formset.defaults.addCssClass = 'btn btn-sm btn-light';
    $.fn.formset.defaults.deleteText = '<i class="icon ion-md-remove"></i>';
    $.fn.formset.defaults.deleteCssClass = 'btn btn-sm btn-danger';
</script>
{% block js %}
{% endblock js %}
<script>
$.fn.datetimepicker.Constructor.Default = $.extend({}, $.fn.datetimepicker.Constructor.Default, {
    icons: {
        time: 'icon ion-md-alarm',
        date: 'icon ion-md-calendar',
        up: 'icon ion-md-arrow-round-up',
        down: 'icon ion-md-arrow-round-down',
        previous: 'icon ion-md-arrow-round-back',
        next: 'icon ion-md-arrow-round-forward',
        today: 'far fa-calendar-check-o',
        clear: 'icon ion-md-trash',
        close: 'icon ion-md-close'
    }
});

$(function() {
    $('form').preventDoubleSubmission()

    var setIconToggleSidebar = function() {
        var colapsado = $('.application-wrapper').hasClass('sidebar-collapsed')
        var iconClass = 'icon ion-md-arrow-back'
        if (colapsado) {
            iconClass = 'icon ion-md-arrow-forward'
        }
        $('.toggle-sidebar').find('i').attr('class', iconClass)
    }

    var hideSubmenus = function() {
        $('.sidebar-collapsed .sidebar [aria-expanded="true"]').attr('aria-expanded', 'false')
        $('.sidebar-collapsed .sidebar .show').removeClass('show')
    }

    var esconderOpcionesMenu = function(){
        $(".sidebar .sub").each(function(){
            if($(this).html().trim() == ""){
                $(this).closest("li").remove();
            }
        })
    }

    var generarBreadcrumb = function(child) {
        var $link = $('.sidebar a[data-child="'+child+'"]')
        var breadcrumbs = []
        var generarHtml = function (b) {
            var $html = $('<div class="d-inline-block"><a href="'+ b.url +'">'+ b.nombre +'</a></div>')
            
            if (b.onClick) {
                $html.find('a').click(function(e) {
                    b.onClick(e)
                })
            }

            return $html
        }

        breadcrumbs.push(generarHtml({url: '/', nombre: 'Inicio'}))

        if ($link.length) {
            $link.addClass('text-primary font-weight-bold')
            // var $parent = $link.closest('[data-parent]').find('[data-toggle="collapse"]')
            var $parent = $link.closest('[data-parent]').find('> a ')
            
            if (!$('.sidebar-collapsed').length) {
                $parent.click()
            }
            
            if ($parent.length) {
                breadcrumbs.push(generarHtml({
                    url: $parent.attr('href'), 
                    nombre: $parent.text().trim(),
                    onClick: function(e) {
                        e.preventDefault()
                        $parent.click()
                    }
                }))
            }

            breadcrumbs.push(generarHtml({
                url: $link.attr('href'), 
                nombre: $link.text().trim()
            }))
        }

        {% if title %}
        breadcrumbs.push(generarHtml({url: '#', nombre: '{{ title }}'}))
        {% endif %}
        $('.app-breadcrums').prepend(breadcrumbs)
    }

    $('.toggle-sidebar').click(function(e) {
        e.preventDefault();
        var colapsado = !$('.application-wrapper').hasClass('sidebar-collapsed')
        $('.application-wrapper').toggleClass('sidebar-collapsed')
        $.ajax({
            url: '{% url "usuarios:set_sidebar" %}',
            type: 'POST',
            data: {colapsado: Number(colapsado)}
        }).done(function(res) {})
        setIconToggleSidebar()
        //setTooltipsSidebar()
        hideSubmenus()
    })

    $('.sidebar-collapsed .sidebar .dropdown-toggle').click(function(e) {
        e.preventDefault()
        var otherLink = $(e.target).attr('aria-expanded') 
        if (otherLink === undefined) {
            otherLink = $(e.target).closest('[aria-expanded]').attr('aria-expanded')
        }

        $(this).tooltip('hide')

        otherLink = (otherLink == "false")

        if (otherLink) {
            hideSubmenus()
        }
    })

    $('.flash-message').click(function() {
        $(this).fadeOut()
    })

    var calendarOpts = {
        format: 'DD/MM/YYYY',
        locale: 'es',
        debug: true
    }

    $(".selectpicker").selectpicker();

    $(".datepicker").each(function(){
        $(this).attr('data-toggle', 'datetimepicker')
        $(this).attr('data-target', '#' + $(this).attr('id'))
        if( $(this).data('format') ) {
            calendarOpts['format'] = $(this).data('format');
            return $(this).datetimepicker(calendarOpts);
        }
        if ($(this).hasClass('validar_fecha_anterior')) {
            calendarOpts['minDate'] = moment()
        }
        if ($(this).hasClass('validar_fecha_posterior')) {
            calendarOpts['maxDate'] = moment()
        }
        $(this).datetimepicker(calendarOpts);
    })

    $('.filtro_exportar .dropdown-item').click(function(){
        var tipo = $(this).data("tipo")
        window.location.href = ".?" + $(this).closest("form").serialize() + "&" + tipo + "=1"
    });

    $("[data-confirm-message]").click(function(e) {
        var $target = $(this)

        if (!$target.data("confirmed")) {
            e.preventDefault()
            var mensaje = $target.attr("data-confirm-message")
            if (!mensaje || mensaje === "") {
                mensaje = "¿Esta seguro que desea continuar?"
            }

            alertify.confirm(mensaje, function(confirmado) {
                if (confirmado) {
                    $target.data("confirmed", true)
                    if ($target.attr("href")) {
                        window.location.href = $target.attr("href")
                    }
                }
            })
        }

    })

    $(".badge-regimen[data-rfc]").each(function(e) {
        var rfc = ($(this).attr("data-rfc") || "").trim()
        if(rfc !== "") {
            setBadgeInfoRegimen($(this), rfc)
        }

    })

    setTimeout(function(){
        $('.flash-message').click()
    }, 4000)

    setIconToggleSidebar()
    generarBreadcrumb('{{ NODO_BREADCRUMB }}')
    esconderOpcionesMenu()
});
</script>
{% endblock _js %}

app/templates/app/catalogo_clientes.html
{% extends "app/base.html" %}
{% load custom_tags %}
{% block contenido %}

<div class="card">

    <div class="card-body">
        <div class="text-right">
            <a href="{% url 'app:agregar_cliente' %}" class="btn btn-primary">Agregar</a>
        </div> 

        <form action="." method="GET">{% csrf_token %}
            <div class="btn-group">
                <div class="list-inline">
                    <div class="align-bottom d-inline-block">
                        Tipo:
                        {{ filtro_form.tipo }} 
                        {{ filtro_form.tipo.errors }}
                    </div>
                    {% include "tools/filtro_form.html" %}
                </div>
            </div>
        </form>

        <div class="table-responsive my-2">
            <table class="table table-striped table-sm table-primary">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Tipo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in list.object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'app:editar_cliente' c.id %}">
                                {{ c.id_admintotal }}
                            </a>
                        </td>

                        <td>
                            <a href="{% url 'app:editar_cliente' c.id %}">
                                {{ c.nombre }}
                            </a>
                        </td>

                        <td>
                            <a href="{% url 'app:editar_cliente' c.id %}">
                                {{ c.show_tipo }}
                            </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock contenido%}

app/templates/app/clean_base.html
{% load static custom_tags thumbnail %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% if title %} {{ title }} | {% endif %}{{ settings.PROJECT_NAME }}</title>
    
    <link href="https://unpkg.com/ionicons@4.5.9-1/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "app/js/jquery-ui-1.12.1/jquery-ui.min.css" %}" />
       

    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "app/bootstrap/4.3.1/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "app/css/custom.css" %}?v=1.1.7">
    <link rel="stylesheet" href="{% static "app/css/app.css" %}?v=1.1.15">

    
    <style>
        .header { background-color: {{ configuracion.color_empresa }}; }
        
    </style>

    <style>
        .ui-datepicker {
        background: #333;
        border: 1px solid #555;
        color: #EEE;
        }
        
        .picker-switch  {
            color: black;
        } 
        .dow  {
            color: black; 
        }
    </style>

    {% if configuracion.logo %}
    <link rel="icon" type="image/png" href="{{ configuracion.logo.url }}">
    {% endif %}

    <script src="{% static "app/js/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "app/js/jquery-ui-1.12.1/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "app/js/jquery.formset.js"%}"></script>
    <script src="{% static "app/js/csrf.js" %}"></script>
    <script src="{% static "app/js/alertify.js" %}?v=1.1.4"></script>

    <script type="text/javascript" src="{% static "tools/js/inputmask.js" %}"></script>
    <script type="text/javascript" src="{% static "tools/js/utils.js" %}?v=1.1.4"></script>


    <script>
    window.urls = {
        ajax_validar_autorizacion: "{% url "usuarios:ajax_validar_autorizacion" "00" %}"
    }
    window.alertify.setConfig({
        container: '#alertifyContainer',
        closeTimeout: 6000,
    });
    window._globals = {
        clave: 'homedepot',
        logging: {
            url: '{{ LOGGER_URL }}/api/v1/log/',
            base_payload: {
                usuario: {
                    id: '{{ request.user.id }}',
                    username: '{{ request.user.username }}',
                }
            }
        },
        palabra_almacen: '{{ inventario.get_palabra_cedis }}',
        dominio: '{{ request.META.HTTP_HOST }}',
        styles: {
            primaryColor: '#001A40',
            dangerColor: '#bc6565',
            successColor: '#509F57',
            secondaryColor: '#18BFD5',
        }
    };
    
    window.getMapMarker = function() {
        return {
            url: '{% static "direcciones/img/map-marker-small.png" %}',
            size: new google.maps.Size(35, 35),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 35)
        }
    };


    window.googleMapDefault = {
        scrollwheel: false,
        maxZoom: 17,
        styles: [{"featureType":"all","stylers":[{"saturation":0},{"hue":"#e7ecf0"}]},{"featureType":"road","stylers":[{"saturation":-70}]},{"featureType":"transit","stylers":[{"visibility":"off"}]},{"featureType":"poi","stylers":[{"visibility":"off"}]},{"featureType":"water","stylers":[{"visibility":"simplified"},{"saturation":-60}]}]
    };

    function showLoading() {
        $('.global-loading').fadeIn("fast")
    }

    function hideLoading() {
        $('.global-loading').fadeOut("fast")
    };
    </script>

    {% block _extra_head %}
    {% block extra_head %}
    {% endblock extra_head %}
    {% endblock _extra_head %}

    <style>
    {% include "app/includes/styles.css" %}    
    </style>
  </head>
  <body>
    <div class="container-alertify" id="alertifyContainer"></div>
    {% block _contenido %}
    {% block contenido %}
    {% endblock contenido %}
    {% endblock _contenido %}
    
    <!-- Global loading -->
    <div class="global-loading">
        <div class="lds-ring"><div></div><div></div><div></div><div></div></div>
    </div>

    <!-- Alertify Confirm Modal -->
    <div class="modal fade" id="alertifyConfirmModal" tabindex="-1">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirme para continuar</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" id = "btnCerrarModal" class="btn btn-secondary btn-confirm-cerrar" data-dismiss="modal">Cerrar</button>
            <button type="button" id ="btnContinuarModal" class="btn btn-primary btn-confirm-continuar">Continuar</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <script src="{% static "app/js/popper.min.js" %}"></script>
    <script src="{% static "app/bootstrap/4.3.1/js/bootstrap.min.js" %}"></script>
    {% block _js %}
    {% block js %}
    {% endblock js %}
    {% endblock _js %}
    
    <script>
    function setLogoBanco(codigo) {
        var $logoBancoImg = $(".logo-banco")

        if ($logoBancoImg.length) {
            $logoBancoImg.empty()
            $logoBancoImg.append('<img height="30px" src="https://soporte.admintotal.com/central_upload/bancos_central/'+ codigo +'.png" />')
        }
    }

    $(function() {
        var ajaxPendientes = {}
        // global loading
        $(document).ajaxStart(function(event, xhr, options) {
            ajaxPendientes[event.time] = 1
            showLoading()
        })
        $(document).ajaxComplete(function(event, xhr, options) {
            delete ajaxPendientes[event.time]
            if (!Object.keys(ajaxPendientes).length) {
                hideLoading()
            }
        })

        $(".autocomplete-banco").autocomplete({
            source: [
                {% for codigo, nombre in BANCOS.items %}
                {
                    label: "{{ codigo }}-{{ nombre }}", 
                    value: "{{ codigo }}-{{ nombre }}", 
                    codigo: "{{ codigo }}", 
                    img: "https://soporte.admintotal.com/central_upload/bancos_central/{{ codigo }}.png"
                },
                {% endfor %}
            ],
            select: function(e, ui) {
                setLogoBanco(ui.item.codigo)
            }
        })

        $(".autocomplete-banco").each(function() {
            var codigoBanco = ($(this).val() || "").split("-")
            if (codigoBanco.length && codigoBanco[0] !== "") {
                setLogoBanco(codigoBanco[0])

            }
        })
    });
    </script>
  </body>
</html>

app/templates/app/dashboard.html
{% extends "app/base.html" %}

{% block extra_head %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
{% endblock extra_head %}

{% block contenido %}
<!-- 
<div class="container-fluid">
	<div class="row">
		<div class="col-md-5">
			<div class="card card-body">
				<div>
					<div id="canvas-holder">
						<canvas style="height:300px" id="chart-area"></canvas>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-7">
			<div class="card card-body">
				<div>
					<h5 class="text-uppercase">Últimas solicitudes</h5>
					<div class="table-responsive">
						<table class="table table-striped table-sm">
							<thead>
								<tr>
									<th>Status</th>
									<th>Folio</th>
									<th>Fecha</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
-->
{% endblock contenido %}

{% block js %}
<script>
	var randomScalingFactor = function() {
		return Math.round(Math.random() * 100);
	};

	var config = {
		type: 'doughnut',
		data: {
			datasets: [{
				data: [
					3,
					2,
					5,
					9,
				],
				backgroundColor: [
					"#b32929",
					"#d2642c",
					"#deb536",
					"#3ca978",
				],
			}],
			labels: [
				'Vencidas',
				'Rechazadas',
				'Sol. Información',
				'Aprobadas',
			]
		},
		options: {
			responsive: true,
			legend: {
				position: 'top',
			},
			title: {
				display: false,
			},
			animation: {
				animateRotate: true
			}
		}
	};

	window.onload = function() {
		/*var ctx = document.getElementById('chart-area').getContext('2d');
		window.myDoughnut = new Chart(ctx, config);*/
	};


</script>
{% endblock js %}

app/templates/app/regenerar_kardex.html
{% extends "app/base.html" %}
{% load custom_tags %}
{% block contenido %}

<form method="post" action=".">{% csrf_token %}
    <div class="card">
        <div class="card-body">
            
            <div class="table-responsive my-2">
                {{ form.fecha }}
                <input type="submit" value="Regenerar"/>
            </div>
        </div>
    </div>
</form>

{% endblock contenido%}