app/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import views

#app_name = "homedepot"


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    
    # ...
]

app_patterns = ([
    path("", views.index, name="index"),
    path("kardex_entradas_almacen/", views.kardex_entradas_almacen, name="kardex_entradas_almacen"),
    path("kardex_almacen/", views.kardex_almacen, name="kardex_almacen"),
    path("contador_usados/", views.contador_usados, name="contador_usados"),
    path("kardex/", views.kardex_usados, name="kardex"),
    path("salidas_proveedor/", views.salidas_proveedor, name="salidas_proveedor"),
    path("kardex_garantia/", views.kardex_garantia, name="kardex_garantia"),
    path("contador_cliente/<int:id>/", views.contador_cliente, name="contador_cliente"),
    path("sincronizar_kardex/", views.sincronizar_kardex, name="sincronizar_kardex"),
    path("regenerar_existencias_kardex/", views.regenerar_existencias_kardex, name="regenerar_existencias_kardex"),
    path("catalogo_cascos/", views.catalogo_cascos, name="catalogo_cascos"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    path("configuracion_inventario/", views.configuracion_inventario, name="configuracion_inventario"),
    
    path("catalogo_clientes/", views.catalogo_clientes, name="catalogo_clientes"),
    path("agregar_casco/", views.agregar_casco, name="agregar_casco"),
    path("agregar_cliente/", views.agregar_cliente, name="agregar_cliente"),
    path("editar_casco/<int:id>", views.editar_casco, name="editar_casco"),
    path("editar_cliente/<int:id>", views.editar_cliente, name="editar_cliente"),
    path("agregar_entrada/", views.agregar_entrada, name="agregar_entrada"),
    path("agregar_salida_garantia_proveedor/",views.agregar_salida_garantia_proveedor, name="agregar_salida_garantia_proveedor"),
    path("agregar_salida_usado_proveedor/",views.agregar_salida_usado_proveedor, name="agregar_salida_usado_proveedor"),
    path("agregar_salida/", views.agregar_salida, name="agregar_salida"),
    path("graficas_movimientos/", views.graficas_movimientos, name="graficas_movimientos"),
    path("cancelar_movimiento/<int:id>", views.cancelar_movimiento, name="cancelar_movimiento"),
    
    path("ver_vale/<int:id>/", views.ver_vale, name="ver_vale"),
    #paht("nota_de_credito/<int:id>", views.ver_nota_de_credito, name="ver_nota_de_credito"),
    path("notas_credito/", views.notas_credito, name="notas_credito"),
    path("nota_credito/<int:id>", views.nota_credito, name="nota_credito"),
    path("agregar_nota_credito/<int:id>", views.agregar_nota_credito, name="agregar_nota_credito"),
    path("gmroi_cliente/<int:id>", views.gmroi_cliente, name="gmroi_cliente"),

    path("ordenes_compra_domicilio/", views.ordenes_compra_domicilio, name="ordenes_compra_domicilio"),
    path("agregar_orden_compra_domicilio/", views.agregar_orden_compra_domicilio, name="agregar_orden_compra_domicilio"),
    path("ajax_get_cliente/<str:term>/", views.ajax_get_cliente, name="ajax_get_cliente"),
    path("ajax_clientes_ac/", views.ajax_clientes_ac, name="ajax_clientes_ac"),
    path("ajax_crear_nota_credito/", views.ajax_crear_nota_credito, name="ajax_crear_nota_credito"),
    path("ajax_get_folios_by_proveedor/", views.ajax_get_folios_by_proveedor,name="ajax_get_folios_by_proveedor"),
    path('sentry-debug/', trigger_error),

    
], "app")

urlpatterns = [
    path("", include(app_patterns)),

    path("configuracion/", include("configuracion.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("atshell/", include("atshell.urls")),
]

# archivos subidos al sistema
urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# static files
urlpatterns = urlpatterns + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

usuarios/urls.py
from usuarios import views
from django.urls import path

app_name = "usuarios"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("acceso_denegado/", views.acceso_denegado, name="acceso_denegado"),
    path("", views.usuarios, name="usuarios"),
    path("roles", views.roles, name="roles"),
    path("perfil", views.perfil, name="perfil"),
    path("editar_usuario/<int:id>/", views.usuario, name="usuario"),
    path("agregar_usuario/", views.usuario, name="usuario"),
    path("inicios_sesion/", views.inicios_sesion, name="inicios_sesion"),
    path("importar_usuarios/", views.importar_usuarios, name="importar_usuarios"),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("reset_password/<str:token>/", views.reset_password, name="reset_password"),
    path(
        "reenviar_correo_bienvenida/<int:id>/",
        views.reenviar_correo_bienvenida,
        name="reenviar_correo_bienvenida",
    ),
    path(
        "ajax/cambiar_password/",
        views.cambiar_password,
        name="cambiar_password",
    ),
    path(
        "ajax/validar_autorizacion/<int:id>/",
        views.ajax_validar_autorizacion,
        name="ajax_validar_autorizacion",
    ),
    path("agregar_rol/", views.agregar_rol, name="agregar_rol"),
    path("editar_rol/<int:id>/", views.editar_rol, name="editar_rol"),
    path("eliminar_rol/<int:id>/", views.eliminar_rol, name="eliminar_rol"),
    # ajax
    path("ajax/set_sidebar/", views.ajax_set_sidebar, name="set_sidebar"),
    path(
        "ajax/set_permiso_rol/<int:id>/",
        views.ajax_set_permiso_rol,
        name="set_permiso_rol",
    ),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from tools.functions import send_email, localtime
from django.utils.functional import cached_property
from django.contrib.postgres.fields import ArrayField
from tools.functions import date_to_str, set_crontab
from django.urls import reverse
import pytz
import uuid
import datetime

class Rol(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    permisos = ArrayField(models.CharField(max_length=255), null=True)

    class Meta:
        ordering = ("nombre",)

    def __str__(self):
        return self.nombre


class Perfil(models.Model):
    """Modelo de perfil de usuario."""

    MX_TIMEZONES = [(x, x) for x in pytz.country_timezones["MX"]]

    usuario_creado = models.ForeignKey(User, null=True, related_name="usuarios_creados", on_delete=models.CASCADE)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=100, null=True, blank=True)
    telefono_extension = models.CharField(max_length=20, null=True, blank=True)
    firma = models.ImageField(upload_to="firmas", null=True, blank=True)
    sidebar_colapsado = models.BooleanField(default=False)
    zona_horaria = models.CharField(
        max_length=255,
        choices=MX_TIMEZONES,
        null=True,
        blank=True,
        default="America/Mexico_City",
        verbose_name="Zona Horaria",
    )
    tema_tamano_fuente = models.CharField(
        max_length=50, blank=True, null=True, default="14"
    )
    token_reset_password = models.CharField(
        max_length=255, unique=True, null=True
    )
    roles = models.ManyToManyField(Rol, related_name="usuarios")


    def __str__(self):
        return "Perfil de usuario {}".format(self.usuario)

    def get_absolute_url(self):
        return reverse("usuarios:usuario", args=[
            self.usuario_id
        ])

    @property
    def nombre(self):
        return self.usuario.first_name

    @property
    def apellidos(self):
        return self.usuario.last_name
    @property
    def telefonos(self):
        return self.usuario.telefono

    @classmethod
    def get_user_objects(cls, vars):
        objects = User.objects.all()
        q = vars.get("q", "")
        cedis = vars.get("cedis")
        centro_responsabilidad = vars.get("choices")
        status = vars.get("status")

        objects = objects.filter(
            models.Q(username__icontains=q) |
            models.Q(first_name__icontains=q) | 
            models.Q(last_name__icontains=q)
        )

        if status == "activos" or not status:
            objects = objects.filter(is_active=True)
        elif status == "inactivos":
            objects = objects.filter(is_active=False)

        if cedis:
            objects = objects.filter(perfil__cedis=cedis)

        if centro_responsabilidad:
            objects = objects.filter(
                perfil__centro_responsabilidad_id=centro_responsabilidad
            )

        objects = objects.order_by('username')
        return objects

    @cached_property
    def get_roles(self):
        """
        Obtiene roles del perfil más los roles  de las suplencias
        """
        roles = self.roles.all()
        for p in Perfil.objects.filter(suplencia=self.usuario):
            roles = roles | p.roles.all()
        return roles
    
    @cached_property
    def permisos_roles(self):
        """
        Retorna una lista con los permisos de los roles que se
        tienen asignados para este perfil.
        """
        permisos = []
        for p in self.roles.values_list("permisos", flat=True):
            permisos += p
        return permisos

    @cached_property
    def permisos_suplencias(self):
        """
        Retorna una lista con los permisos de las suplencias que se
        tienen asignadas para este perfil.
        """
        suplencias = []
        hoy = localtime().date()
        objects = Perfil.objects.filter(
            suplencia=self.usuario,
            suplencia_desde__lte=hoy,
            suplencia_hasta__gte=hoy
        )
        for p in objects.values_list("roles__permisos", flat=True):
            suplencias += p

        return suplencias

    def tiene_permiso(self, permiso):
        """Validación de permiso de un usuario."""
        if self.usuario.is_superuser:
            return True

        permisos = self.permisos_roles
        suplencias = self.permisos_suplencias
        return permiso in set(permisos + suplencias)

    def notificar_cambio_password(self):
        """Enviamos correo de bienvenida al usuario"""
        email = self.usuario.email

        if not email:
            return False

        return send_email(
            to=[email],
            subject="Cambio de contraseña",
            template={
                "name": "usuarios/emails/cambio_password.html",
                "context": {"perfil": self},
            },
        )

    def notificar_inicio_suplencia(self):
        """
        Docs
        """
        from configuracion.models import Configuracion
        if not self.suplencia or not self.suplencia.email:
            return False

        email = self.suplencia.email
        c = Configuracion.objects.get()
        html_mensaje = c.get_html_mensaje(
            field="html_mensaje_inicio_suplencia",
            placeholders={
                "_usuario_suplantante_": self.suplencia.get_full_name(),
                "_usuario_suplantado_": self.usuario.get_full_name(),
                "_fecha_inicio_suplencia_": self.suplencia_desde.strftime("%d/%m/%Y"),
                "_fecha_fin_suplencia_": self.suplencia_hasta.strftime("%d/%m/%Y"),
            }
        )
        set_crontab(
            "notificar_fin_suplencia",
            setall="{} *".format(self.suplencia_hasta.strftime("30 11 %d %m")),
            command_opts={"--id": self.id},
            auto_delete=True,
        )
        return send_email(
            to=[email],
            subject="Notificación nueva suplencia",
            template={
                "name": "usuarios/emails/suplencia.html",
                "context": { "perfil": self, "html_mensaje": html_mensaje},
            },
        )

    def notificar_fin_suplencia(self):
        """
        Docs
        """
        from configuracion.models import Configuracion
        if not self.suplencia or not self.suplencia.email:
            return False

        email = self.suplencia.email
        c = Configuracion.objects.get()
        html_mensaje = c.get_html_mensaje(
            field="html_mensaje_fin_suplencia",
            placeholders={
                "_usuario_suplantante_": self.suplencia.get_full_name(),
                "_usuario_suplantado_": self.usuario.get_full_name(),
                "_fecha_inicio_suplencia_": self.suplencia_desde.strftime("%d/%m/%Y"),
                "_fecha_fin_suplencia_": self.suplencia_hasta.strftime("%d/%m/%Y"),
            }
        )
        return send_email(
            to=[email],
            subject="Finalización de suplencia",
            template={
                "name": "usuarios/emails/suplencia.html",
                "context": { "perfil": self, "html_mensaje": html_mensaje},
            },
        )

    def enviar_email_bienvenida(self):
        """Enviamos correo de bienvenida al usuario"""
        email = self.usuario.email

        if not email:
            return False

        return send_email(
            to=[email],
            subject="Correo de bienvenida",
            template={
                "name": "usuarios/emails/correo_bienvenida.html",
                "context": {"perfil": self},
            },
        )

    def set_token_reset_password(self):
        """Asigna el token para el cambio de contraseña."""
        token = str(uuid.uuid1())
        while Perfil.objects.filter(token_reset_password=token).exists():
            token = str(uuid.uuid1())

        self.token_reset_password = token
        
    def enviar_email_reset_password(self):
        """Envía correo con liga para asignar nueva contraseña"""
        from configuracion.models import Configuracion
        email = self.usuario.email

        if not email:
            return False

        configuracion = Configuracion.objects.get()
        
        self.set_token_reset_password()
        self.save()

        return send_email(
            to=[email],
            subject="Solicitud de cambio de contraseña",
            template={
                "name": "usuarios/emails/reset_password.html",
                "context": {
                    "perfil": self,
                    "link_reset_password": "{}{}".format(
                        configuracion.get_url_proyecto(),
                        reverse(
                            "usuarios:reset_password", 
                            args=[self.token_reset_password]
                        )
                    )
                },
            },
        )

class InicioSesion(models.Model):
    ip = models.CharField(max_length=50)
    usuario = models.ForeignKey(
        User, 
        related_name="inicio_sesiones", 
        on_delete=models.PROTECT,
        null=True
    )
    nombre_usuario = models.CharField(max_length=255, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    user_agent = models.CharField(max_length=255)
    exitoso = models.BooleanField(default=False)
    motivo = models.TextField()

    class Meta:
        ordering = ("-fecha",)

    def __str__(self):
        return "[{}] {} - {}".format(
            self.ip, 
            date_to_str(self.fecha), 
            self.user
        )

    @classmethod
    def get_objects(cls, vars):
        objects = cls.objects.all()
        q = vars.get("q", "")
        if q:
            objects = objects.filter(
                models.Q(user_agent__icontains=q)
                | models.Q(nombre_usuario__icontains=q)
                | models.Q(ip__icontains=q)
            )
        return objects

usuarios/templates/usuarios/acceso_denegado.html
{% extends template_base %}

{% block contenido %}
<div class="card m-4">
	<div class="card-body text-center">
		<h1 class="text-danger m-0" style="font-size: 7em;"><i class="icon ion-md-lock"></i></h1>
		<h3 class="text-danger">Acceso Denegado</h3>
		{% if permiso %}
		<p class="lead">No cuenta con el permiso <b>{{ permiso }}</b>.</p>
		{% endif %}

		{% if request.GET.next %}
			<a href="{{ request.GET.next }}" id="VolverIntentar" class="btn btn-primary">Volver a intentar</a>
		{% endif %}
	</div>
</div>
{% endblock contenido %}

usuarios/templates/usuarios/roles.html
{% extends "app/base.html" %}
{% load custom_tags %}

{% block extra_head %}
<style>
.permiso-toggle-td input{
	visibility: hidden;
	width: 1px;
	height: 1px;
}
.permisos-roles-table th{
	line-height: 1.1;
	font-size: .9em;
	vertical-align: middle;
	padding-bottom: 0;
}
</style>
{% endblock extra_head %}

{% block contenido %}
<div class="text-right mb-2">
	<button class="btn btn-primary agregar-rol">Agregar Rol</button>
</div>
<div class="table-responsive">
	<table class="table table-primary table-sm table-hover permisos-roles-table">
		<thead>
			<tr>
				<th style="width:430px;padding-bottom:10px">Permiso</th>
				{% for rol in roles %}
				<th class="text-center" style="min-width:110px">
					{{ rol.nombre }} 
					<div>
						<a title="Seleccionar todo" href="#" class="btn btn-sm toggle-all" data-id="{{ rol.id }}">
							<i class="icon ion-md-checkbox-outline"></i>
						</a>
						<a title="Editar rol" class="btn btn-sm editar-rol" href="#" data-nombre="{{ rol.nombre }}" data-id="{{ rol.id }}">
							<i class="icon ion-md-create"></i>
						</a>
						<a data-confirm-message="¿Esta seguro que desea eliminar el rol {{ rol.nombre }}?" title="Eliminar rol" class="btn btn-sm" href="{% url "usuarios:eliminar_rol" rol.id %}">
							<i class="icon ion-md-trash"></i>
						</a>
					</div>
				</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody id="permisosBodyTable">
			{% with 20 as padding %}
			{% for node in PERMISOS_UBICACIONES %}
				{% include "usuarios/includes/permiso_nodo.html" %}
			{% endfor %}
			{% endwith %}
		</tbody>
	</table>
</div>

<div id="rolModal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="" method="POST">
				<input type="hidden" name="agregar_url" value="{% url "usuarios:agregar_rol" %}">
				<input type="hidden" name="editar_url" value="{% url "usuarios:editar_rol" 1 %}">

				{% csrf_token %}
				<input type="hidden" name="back_url" value="{{ request.path }}">
				<div class="modal-header">
			        <h5 class="modal-title">Agregar Rol</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        <div class="form-group nuevo_pass">
			        	<label for="">Nombre:</label>
			        	<input type="text" name="nombre" id="nombre_rol" class="form-control" required>
			        </div>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			        <button type="submit" class="btn btn-primary btn-guardar">Guardar</button>
			      </div>
			</form>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block js %}
<script>
$(function() {
	var guardarPermisoRol = function(permiso, rol, habilitado) {
		$.ajax({
			url: '{% url "usuarios:set_permiso_rol" 1 %}'.replace("1", rol),
			type:'POST',
			data: {"permiso": permiso, "habilitado": Number(habilitado)}
		}).done(function(response) {
			console.log(response)
		})
	}

	var $rolModal = $("#rolModal")
	var $rolFoModalForm = $rolModal.find('form')
	var $rolModalTitle = $rolModal.find(".modal-title")
	var $rolModalGuardar = $rolModal.find(".btn-guardar")

	var agregarRol = function(e) {
		e.preventDefault()
		$('#rolModal').modal()
		var url = $rolModal.find('[name="agregar_url"]').val()
		$rolFoModalForm.attr('action', url)
		$rolFoModalForm.find('[name="nombre"]').val("")
		$rolModalTitle.text("Agregar rol")
		$rolModalGuardar.text("Guardar")
	}

	var seleccionarTodo = function(e) {
		e.preventDefault()
		var id = $(this).data('id')
		$('button[data-rol="'+id+'"]').click()
	}

	var editarRol = function(e) {
		e.preventDefault()
		$('#rolModal').modal()
		var id = $(this).data("id")
		var nombre = $(this).data("nombre")
		var url = $rolModal.find('[name="editar_url"]').val().replace("1", id)
		$rolFoModalForm.find('[name="nombre"]').val(nombre)
		$rolFoModalForm.attr('action', url)
		$rolModalTitle.text("Editar rol")
		$rolModalGuardar.text("Editar Rol")
	}

	// al mostrarse el modal focus al input nombre
	$rolModal.on('shown.bs.modal', function (e) {
		$rolFoModalForm.find('[name="nombre"]').select()
	})

	// eventos click
	$('.agregar-rol').click(agregarRol)
	$('.editar-rol').click(editarRol)
	$('.toggle-permiso').click(function(e) {
		e.preventDefault()

		var $checkbox = $(this).siblings('input').eq(0)
		var checked = !$checkbox.is(':checked')
		var permiso = $(this).data('permiso')
		var rol = $(this).data('rol')

		$checkbox.prop('checked', checked)

		if (checked) {
			$(this)
			.removeClass('btn-gray')
			.addClass('btn-success')
			.html('<i class="icon ion-md-checkmark-circle"></i>')
		} else {
			$(this)
			.removeClass('btn-success')
			.addClass('btn-gray')
			.html('<i class="icon ion-md-close-circle"></i>')
		}

		guardarPermisoRol(permiso, rol, checked)
	})

	$('.toggle-all').click(seleccionarTodo)
});
</script>
{% endblock js %}

usuarios/templates/usuarios/usuario.html
{% extends "app/base.html" %}

{% block extra_head %}
<style>
ul#id_roles, 
ul#id_cedis{
	list-style: none;
	padding: 0;
	margin: 2px 0;
	/*max-height: 20vh;*/
    padding-left: 15px;
    overflow: auto;
}
</style>
{% endblock extra_head %}

{% block contenido %}
<form action="" method="POST" enctype="multipart/form-data" autocomplete="off">
	{% csrf_token %}
	<div class="card my-2">
		<div class="card-body">
			<div class="row">
				<div class="col-md-8">
					<div class="form-check form-check-inline">
						{{ form.is_active.label_tag }}
						{{ form.is_active.errors }}
						{{ form.is_active }}
					</div>
					<hr>
					<div class="form-group">
						{{ form.username.label_tag }}
						{{ form.username }}
						{{ form.username.errors }}
						{% if form.instance.id %}
						<a data-toggle="modal" class="my-1 d-inline-block" href="#cambiarPassModal">Cambiar Contraseña</a>
						{% endif %}
					</div>

					{% if not form.instance.id %}
					<div class="form-group nuevo_pass">
						{{ form.password.label_tag }}
						{{ form.password }}
						{{ form.password.errors }}
					</div>
					<div class="form-group re_nuevo_pass">
						{{ form.re_password.label_tag }}
						{{ form.re_password }}
						{{ form.re_password.errors }}
					</div>
					{% endif %}

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								{{ form.first_name.label_tag }}
								{{ form.first_name }}
								{{ form.first_name.errors }}
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{{ form.last_name.label_tag }}
								{{ form.last_name }}
								{{ form.last_name.errors }}
							</div>
						</div>
					</div>
					<div class="form-group">
						{{ form.email.label_tag }}
						{{ form.email }}
						{{ form.email.errors }}
					</div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								{{ form.roles.label_tag }}
								{{ form.roles }}
								{{ form.roles.errors }}
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						{{ form.zona_horaria.label_tag }}
						{{ form.zona_horaria }}
						{{ form.zona_horaria.errors }}
					</div>
					<div class="form-group">
						{{ form.tema_tamano_fuente.label_tag }}
						{{ form.tema_tamano_fuente }}
						{{ form.tema_tamano_fuente.errors }}
					</div>
					<div class="form-group">
						{{ form.firma.label_tag }}
						{{ form.firma }}
						{{ form.firma.errors }}
					</div>
					<div class="form-group">
						{{ form.suplencia.label_tag }}
						{{ form.suplencia }}
						{{ form.suplencia.errors }}
					</div>
					
				</div>
			</div>
		</div>
	</div>

	<div class="text-right">
		{% if form.instance.id and form.instance.email %}
		<a href="{% url 'usuarios:reenviar_correo_bienvenida' form.instance.id %}" id="reenviarBienve" class="btn btn-light">Reenviar correo de bienvenida</a>
		{% endif %}
		<a href="{% url 'usuarios:usuarios' %}" id="usuarioCancel" class="btn btn-light">Cancelar</a>
		<button type="submit" id="guardarUser" class="btn btn-primary">Guardar</button>
	</div>
</form>

<div id="cambiarPassModal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form action="{% url "usuarios:cambiar_password" %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="usuario_id" value="{{ form.instance.id }}">
				<input type="hidden" name="back_url" value="{{ request.path }}">
				<div class="modal-header">
			        <h5 class="modal-title">Cambiar contraseña</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        <div class="form-group nuevo_pass">
			        	<label for="">Nueva contraseña:</label>
			        	<input type="password" name="nuevo_pass" id="nuevo_pass" class="form-control" required>
			        </div>
			        <div class="form-group re_nuevo_pass">
			        	<label for="">Confirmar nueva contraseña:</label>
			        	<input type="password" name="re_nuevo_pass" id="re_nuevo_pass" class="form-control" required>
			        </div>
			      </div>
			      <div class="modal-footer">
			        <button type="button" id="cancelarContra" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			        <button type="submit" id="cambiarContra" class="btn btn-primary btn-guardar">Cambiar Contraseña</button>
			      </div>
			</form>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block js %}
<script>
var GUARDANDO = false
var cedisData = {
	{% for cedis in form.fields.cedis.queryset %}
	"{{ cedis.id }}": {
		id: "{{ cedis.id }}",
		text: "{{ cedis }}",
		centros_responabilidad: [
			{% for cr in cedis.centros_responabilidad.all %}
				{
					id: "{{ cr.id }}",
					text: "{{ cr }}",
				},
			{% endfor %}
		]
	},
	{% endfor %}
};

function validarConfirmacionPassord() {
	var nuevo_pass = $('.nuevo_pass input').val()
	var re_nuevo_pass = $('.re_nuevo_pass input').val()

	if (nuevo_pass !== re_nuevo_pass) {
		alertify.error('Las contraseñas no coinciden.')
		$('.re_nuevo_pass input').select()
		return false
	}

	return true
}

function setCentrosResponsabilidadOptions() {
	var optionsCR = []
	var initialCR = $("#id_centro_responsabilidad").attr("value")
	
	$('[name="cedis"]:checked').each(function() {
		$(cedisData[$(this).val()].centros_responabilidad).each(function() {
			var opt = "<option value="+this.id+">"+this.text+"</option>"
			if (optionsCR.indexOf(opt) === -1) {
				optionsCR.push(opt)
			}
		})
	})

	$("#id_centro_responsabilidad").html(optionsCR)
	$("#id_centro_responsabilidad").val(initialCR)

}

$(function() {
	$('.re_nuevo_pass input').change(validarConfirmacionPassord)
	$('[name="cedis"]').change(setCentrosResponsabilidadOptions)
	setCentrosResponsabilidadOptions()
});
</script>
{% endblock js %}